<a href="https://colab.research.google.com/github/pratikwatwani/Applied-Data-Science/blob/master/Session%2011/Neural%20Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 7_Session 11. Neural networks

The purpose of the below is to classify days over years 2017-2018 by their corresponding mobility patterns between 10 zones in Taipei (quantified by an aggregated temporal network of subway ridership flows across the city)

In [1]:
#use Python 3.7
import numpy as np
import pandas as pd
import keras
from keras.datasets import mnist
from sklearn.preprocessing import MinMaxScaler
from keras.models import Model, Sequential
from keras.layers import Input, Dense
from keras.utils import np_utils

Using TensorFlow backend.


In [0]:
#read the data
TNet=pd.read_csv('https://raw.githubusercontent.com/pratikwatwani/Applied-Data-Science/master/data/taipeiD_TNet2.csv',header=None);

In [3]:
TNet.head() 
#each row represents a 10x10 adjacency matrix of the normalized Taipei subway mobility network between 10 zones flattened into a 100x1 row corresponding to a single day
#days start at jan-1-2017

0         1         2   ...        97        98        99
0  0.017943  0.005415  0.003590  ...  0.011075  0.005073  0.012708
1  0.021283  0.005215  0.003530  ...  0.009618  0.005946  0.013709
2  0.028988  0.006511  0.005591  ...  0.008791  0.010040  0.016301
3  0.029534  0.006471  0.005615  ...  0.008729  0.010296  0.016437
4  0.029333  0.006525  0.005727  ...  0.008923  0.010381  0.016914

[5 rows x 100 columns]

In [0]:
#convert to an array and scale the data
X=np.array(TNet);

In [0]:
X=MinMaxScaler(feature_range=(0, 1), copy=True).fit_transform(X)

In [6]:
X.shape

(669, 100)

In [7]:
#define day of the week corresponding to each day of observation; 0-Sunday, 1-Monday,...,6-Saturday
y=np.array(range(669))%7; y[:10]

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [8]:
yc=np_utils.to_categorical(y) #get categorical binary variables isSunday, isMonday,...
yc[:5]

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [0]:
X_test=X[400:,:]; X_train=X[:400,:]; #split the data into training and test
y_test=yc[400:,:]; y_train=yc[:400,:]
dim = X_train.shape[1]

In [10]:
print(X_test.shape)
print(X_train.shape)
print(y_train.shape)
print(y_test.shape)

(269, 100)
(400, 100)
(400, 7)
(269, 7)


## Task 1. Classify weekdays/weekends
Label the rows with ones for weekends, zeros for weekdays.
Train a neural network with 4 layers of 30,10,3 and 1 (output) neurons over the training sample against this label, evaluating its performance over the test sample. Report the acheived accuracy (categorical) over the test sample

First three layers use relu activation function, last one - sigmoid.
Use loss='binary_crossentropy', optimizer='adam', 100 epochs, batch_size=20. 

In [11]:
y

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
       0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,

In [12]:
y_c = y
for idx, item in enumerate(y_c):
  if ((item == 0)| (item == 6)):
    y_c[idx] = 1
  else:
    y_c[idx] = 0

y_c

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,

In [0]:
y1_train=y_c[:400]
y1_test=y_c[400:]

In [14]:
print(y1_train.shape)
print(y1_test.shape)


(400,)
(269,)


In [15]:
np.random.seed(1612)
test = pd.DataFrame()
model = Sequential()
model.add(Dense(30, activation='relu', input_dim=dim))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y1_train, validation_data=(X_test, y1_test), epochs=100, batch_size=20, verbose=2)
test = model.predict(X_test)






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 400 samples, validate on 269 samples
Epoch 1/100





 - 0s - loss: 0.4330 - acc: 0.7125 - val_loss: 0.3422 - val_acc: 0.7175
Epoch 2/100
 - 0s - loss: 0.3220 - acc: 0.7125 - val_loss: 0.2880 - val_acc: 0.7175
Epoch 3/100
 - 0s - loss: 0.2805 - acc: 0.7350 - val_loss: 0.2581 - val_acc: 0.7955
Epoch 4/100
 - 0s - loss: 0.2407 - acc: 0.9300 - val_loss: 0.2128 - val_acc: 0.9554
Epoch 5/100
 - 0s - loss: 0.2041 - acc: 0.9525 - val_loss: 0.1830 - val_acc: 0.9554
Epoch 6/100
 - 0s - loss: 0.1761 - acc: 0.9525 - val_loss: 0.1605 - val_acc: 0.9554
Epoch 7/100
 - 0s - loss: 0.1547 - acc: 0.9525 - val_loss: 0.1456 - val_acc: 0.9554
Epoch 8/100
 - 0s - loss: 0.1423 - acc: 0.9525 - val_loss: 0.1371 - val_acc: 0.9554
Epoch 9/100
 - 0s - loss: 0.1370 - acc: 0.9525 - val_loss: 0.1313 - val_acc: 0.9554
Epoch 10/100
 - 0s - loss: 0.1319 - acc: 0.9525 - val_loss: 0.1279 - val_acc: 0.9554
Epoch 

In [16]:
acc_df = pd.DataFrame()
acc_df['predict'] = test.flatten()
acc_df.head()

predict
0  0.000004
1  0.000009
2  0.000002
3  0.000001
4  0.000044

In [17]:
acc_df['labels'] = y1_test
acc_df.head(10)

predict  labels
0  0.000004       0
1  0.000009       0
2  0.000002       0
3  0.000001       0
4  0.000044       0
5  0.999995       1
6  0.999994       1
7  0.000007       0
8  0.000015       0
9  0.000657       0

In [18]:
print("Accuracy is: {}\nBUDAM BUM!!".format(1.0*sum((acc_df['labels']==1)==(acc_df['predict']>0.5))/len(acc_df['predict'])))

Accuracy is: 0.9739776951672863
BUDAM BUM!!


## Task 2. Classify all days of the week
Train a neural network against the origial categorical label. Use 5 layers of 40,15,5 and 7 (outputs, representing probabilities for a current input to correspond to each of the weekdays) neurons over the training sample, evaluating its performance over the test sample (use 'categorical_accurary'). Report the acheived accuracy (categorical) over the test sample.

First three layers use relu activation function, last one - sigmoid.
Use loss='binary_crossentropy', optimizer='adam', 200 epochs, batch_size=20

In [19]:
y=np.array(range(669))%7; y[:16]

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [0]:
y = list(y)
for i, item in  enumerate(y):
  size = y.count(item)
  y[i] = item/size

In [0]:
y2_train=y[:400]
y2_test=y[400:]

In [22]:
np.random.seed(161219)
model = Sequential()
model.add(Dense(40, activation='relu', input_dim=dim))
model.add(Dense(15, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y2_train, validation_data=(X_test, y2_test), epochs=200, batch_size=20, verbose=2)
test2 = model.predict(X_test)

Train on 400 samples, validate on 269 samples
Epoch 1/200
 - 0s - loss: 0.5991 - acc: 0.1450 - val_loss: 0.6297 - val_acc: 0.1413
Epoch 2/200
 - 0s - loss: 0.3747 - acc: 0.1450 - val_loss: 0.7069 - val_acc: 0.1413
Epoch 3/200
 - 0s - loss: 0.2094 - acc: 0.1450 - val_loss: 1.0466 - val_acc: 0.1413
Epoch 4/200
 - 0s - loss: 0.1980 - acc: 0.1450 - val_loss: 1.0311 - val_acc: 0.1413
Epoch 5/200
 - 0s - loss: 0.1957 - acc: 0.1450 - val_loss: 0.9698 - val_acc: 0.1413
Epoch 6/200
 - 0s - loss: 0.1948 - acc: 0.1450 - val_loss: 0.9866 - val_acc: 0.1413
Epoch 7/200
 - 0s - loss: 0.1940 - acc: 0.1450 - val_loss: 0.9789 - val_acc: 0.1413
Epoch 8/200
 - 0s - loss: 0.1932 - acc: 0.1450 - val_loss: 0.9746 - val_acc: 0.1413
Epoch 9/200
 - 0s - loss: 0.1925 - acc: 0.1450 - val_loss: 0.9792 - val_acc: 0.1413
Epoch 10/200
 - 0s - loss: 0.1918 - acc: 0.1450 - val_loss: 0.9767 - val_acc: 0.1413
Epoch 11/200
 - 0s - loss: 0.1913 - acc: 0.1450 - val_loss: 0.9696 - val_acc: 0.1413
Epoch 12/200
 - 0s - loss: 0

In [24]:
acc_df1 = pd.DataFrame()
acc_df1['predict'] = test2.flatten()
acc_df1.head()

predict
0  0.042751
1  0.043002
2  0.050843
3  0.074965
4  0.104316

In [25]:
acc_df1['labels'] = y2_test
acc_df1.head(10)

predict    labels
0  0.042751  0.025641
1  0.043002  0.051282
2  0.050843  0.076923
3  0.074965  0.105263
4  0.104316  0.131579
5  0.044384  0.157895
6  0.001490  0.000000
7  0.051737  0.026316
8  0.057636  0.052632
9  0.059519  0.078947

In [27]:
print("Accuracy is: {}\nDone for this semester!!".format(1.0*sum((acc_df1['labels']==1)==(acc_df1['predict']>0.5))/len(acc_df1['predict'])))

Accuracy is: 0.9814126394052045
Done for this semester!!
