<a href="https://colab.research.google.com/github/pratikwatwani/Applied-Data-Science/blob/master/Session%2011/Neural%20Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural networks


The purpose of the below is to classify days over years 2017-2018 by their corresponding mobility patterns between 10 zones in Taipei (quantified by an aggregated temporal network of subway ridership flows across the city)

In [0]:
#use Python 3.7
import numpy as np
import pandas as pd
import keras
from keras.datasets import mnist
from sklearn.preprocessing import MinMaxScaler
from keras.models import Model, Sequential
from keras.layers import Input, Dense
from keras.utils import np_utils

In [0]:
#read the data
TNet=pd.read_csv('https://raw.githubusercontent.com/pratikwatwani/Applied-Data-Science/master/data/taipeiD_TNet2.csv',header=None);

In [202]:
TNet.head() 
#each row represents a 10x10 adjacency matrix of the normalized Taipei subway mobility network between 10 zones flattened into a 100x1 row corresponding to a single day
#days start at jan-1-2017

0         1         2   ...        97        98        99
0  0.017943  0.005415  0.003590  ...  0.011075  0.005073  0.012708
1  0.021283  0.005215  0.003530  ...  0.009618  0.005946  0.013709
2  0.028988  0.006511  0.005591  ...  0.008791  0.010040  0.016301
3  0.029534  0.006471  0.005615  ...  0.008729  0.010296  0.016437
4  0.029333  0.006525  0.005727  ...  0.008923  0.010381  0.016914

[5 rows x 100 columns]

In [0]:
#convert to an array and scale the data
X=np.array(TNet);

In [0]:
X=MinMaxScaler(feature_range=(0, 1), copy=True).fit_transform(X)

In [205]:
X.shape

(669, 100)

In [206]:
#define day of the week corresponding to each day of observation; 0-Sunday, 1-Monday,...,6-Saturday
y=np.array(range(669))%7; y[:10]

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2])

In [207]:
yc=np_utils.to_categorical(y) #get categorical binary variables isSunday, isMonday,...
yc[:5]

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]], dtype=float32)

In [0]:
X_test=X[400:,:]; X_train=X[:400,:]; #split the data into training and test
y_test=yc[400:,:]; y_train=yc[:400,:]
dim = X_train.shape[1]

In [209]:
print(X_test.shape)
print(X_train.shape)
print(y_train.shape)
print(y_test.shape)

(269, 100)
(400, 100)
(400, 7)
(269, 7)


## Task 1. Classify weekdays/weekends
Label the rows with ones for weekends, zeros for weekdays.
Train a neural network with 4 layers of 30,10,3 and 1 (output) neurons over the training sample against this label, evaluating its performance over the test sample. Report the acheived accuracy (categorical) over the test sample

First three layers use relu activation function, last one - sigmoid.
Use loss='binary_crossentropy', optimizer='adam', 100 epochs, batch_size=20. 

In [210]:
y

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
       0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,

In [211]:
y_c = y
for idx, item in enumerate(y_c):
  if ((item == 0)| (item == 6)):
    y_c[idx] = 1
  else:
    y_c[idx] = 0

y_c

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,

In [0]:
y1_train=y_c[:400]
y1_test=y_c[400:]

In [213]:
print(y1_train.shape)
print(y1_test.shape)


(400,)
(269,)


In [214]:
np.random.seed(1612)
test = pd.DataFrame()
model = Sequential()
model.add(Dense(30, activation='relu', input_dim=dim))
model.add(Dense(10, activation='relu'))
model.add(Dense(3, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y1_train, validation_data=(X_test, y1_test), epochs=100, batch_size=20, verbose=2)
test = model.predict(X_test)

Train on 400 samples, validate on 269 samples
Epoch 1/100
 - 2s - loss: 0.4269 - acc: 0.7125 - val_loss: 0.3396 - val_acc: 0.7175
Epoch 2/100
 - 0s - loss: 0.3198 - acc: 0.7125 - val_loss: 0.2875 - val_acc: 0.7175
Epoch 3/100
 - 0s - loss: 0.2802 - acc: 0.7350 - val_loss: 0.2579 - val_acc: 0.7918
Epoch 4/100
 - 0s - loss: 0.2409 - acc: 0.9300 - val_loss: 0.2130 - val_acc: 0.9554
Epoch 5/100
 - 0s - loss: 0.2046 - acc: 0.9525 - val_loss: 0.1837 - val_acc: 0.9554
Epoch 6/100
 - 0s - loss: 0.1770 - acc: 0.9525 - val_loss: 0.1608 - val_acc: 0.9554
Epoch 7/100
 - 0s - loss: 0.1551 - acc: 0.9525 - val_loss: 0.1446 - val_acc: 0.9554
Epoch 8/100
 - 0s - loss: 0.1413 - acc: 0.9525 - val_loss: 0.1355 - val_acc: 0.9554
Epoch 9/100
 - 0s - loss: 0.1366 - acc: 0.9525 - val_loss: 0.1303 - val_acc: 0.9554
Epoch 10/100
 - 0s - loss: 0.1314 - acc: 0.9525 - val_loss: 0.1271 - val_acc: 0.9554
Epoch 11/100
 - 0s - loss: 0.1331 - acc: 0.9550 - val_loss: 0.1272 - val_acc: 0.9517
Epoch 12/100
 - 0s - loss: 0

In [215]:
acc_df = pd.DataFrame()
acc_df['predict'] = test.flatten()
acc_df.head()

predict
0  0.000001
1  0.000003
2  0.000001
3  0.000001
4  0.000028

In [216]:
acc_df['labels'] = y1_test
acc_df.head(10)

predict  labels
0  0.000001       0
1  0.000003       0
2  0.000001       0
3  0.000001       0
4  0.000028       0
5  0.999996       1
6  0.999995       1
7  0.000003       0
8  0.000007       0
9  0.000703       0

In [217]:
print("Accuracy is: {}\nBUDAM BUM!!".format(1.0*sum((acc_df['labels']==1)==(acc_df['predict']>0.5))/len(acc_df['predict'])))

Accuracy is: 0.9776951672862454
BUDAM BUM!!


## Task 2. Classify all days of the week
Train a neural network against the origial categorical label. Use 5 layers of 40,15,5 and 7 (outputs, representing probabilities for a current input to correspond to each of the weekdays) neurons over the training sample, evaluating its performance over the test sample (use 'categorical_accurary'). Report the acheived accuracy (categorical) over the test sample.

First three layers use relu activation function, last one - sigmoid.
Use loss='binary_crossentropy', optimizer='adam', 200 epochs, batch_size=20

In [235]:
y=np.array(range(669))%7; y[:16]

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1])

In [0]:
'''y = list(y)
for i, item in  enumerate(y):
  size = y.count(item)
  y[i] = item/size
'''

In [0]:
#yg = np_utils.to_categorical(y)

In [0]:
y = np_utils.to_categorical(y)

In [0]:
y2_train=y[:400]
y2_test=y[400:]

In [0]:
'''y2_train=np_utils.to_categorical(y2_train)
y2_test=np_utils.to_categorical(y2_test)
'''

In [0]:
'''y2_test = y2_test.flatten()
y2_train= y2_train.flatten()
'''

In [234]:
np.random.seed(1216)
model = Sequential()
model.add(Dense(40, activation='relu', input_dim=dim))
model.add(Dense(15, activation='relu'))
model.add(Dense(5, activation='relu'))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['categorical_accuracy'])
model.fit(X_train, y2_train, validation_data=(X_test, y2_test), epochs=200, batch_size=20, verbose=2)
test2 = model.predict(X_test)

ValueError: ignored

In [0]:
acc_df1 = pd.DataFrame()
acc_df1['predict'] = test2.flatten()
acc_df1.head()

In [0]:
acc_df1['labels'] = y2_test
acc_df1.head(10)

In [0]:
print("Accuracy is: {}\nDone for this semester!!".format(1.0*sum((acc_df1['labels']==1)==(acc_df1['predict']>0.5))/len(acc_df1['predict'])))